import Image01 from "@/images/user-36-05.jpg";
import Image02 from "@/images/user-36-06.jpg";
import Image03 from "@/images/user-36-07.jpg";
import Image04 from "@/images/user-36-08.jpg";
import Image05 from "@/images/user-36-09.jpg";

export const customersData = [
  {
    id: "0",
    image: Image01,
    name: "Alex Shatov",
    email: "alexshatov@gmail.com",
    location: "🇺🇸",
    spent: "$2,890.66",
    persona: "High-value",
  },
  {
    id: "1",
    image: Image02,
    name: "Philip Harbach",
    email: "philip.h@gmail.com",
    location: "🇩🇪",
    spent: "$2,767.04",
    persona: "High-value",
  },
  {
    id: "2",
    image: Image03,
    name: "Mirko Fisuk",
    email: "mirkofisuk@gmail.com",
    location: "🇫🇷",
    spent: "$2,996.00",
    persona: "High-value",
  },
  {
    id: "3",
    image: Image04,
    name: "Olga Semklo",
    email: "olga.s@cool.design",
    location: "🇮🇹",
    spent: "$1,220.66",
    persona: "Engaged but low spending",
  },
  {
    id: "4",
    image: Image05,
    name: "Burak Long",
    email: "longburak@gmail.com",
    location: "🇬🇧",
    spent: "$1,890.66",
    persona: "Likely to churn",
  },
  {
    id: "5",
    image: Image01,
    name: "Sara Lee",
    email: "sara.lee@email.com",
    location: "🇨🇦",
    spent: "$1,500.00",
    persona: "New customer",
  },
  {
    id: "6",
    image: Image02,
    name: "John Doe",
    email: "john.doe@email.com",
    location: "🇦🇺",
    spent: "$3,200.50",
    persona: "High-value",
  },
  {
    id: "7",
    image: Image03,
    name: "Priya Singh",
    email: "priya.singh@email.com",
    location: "🇮🇳",
    spent: "$950.00",
    persona: "Engaged but low spending",
  },
  {
    id: "8",
    image: Image04,
    name: "Carlos Mendez",
    email: "carlos.m@email.com",
    location: "🇪🇸",
    spent: "$2,100.75",
    persona: "Likely to churn",
  },
  {
    id: "9",
    image: Image05,
    name: "Emily Chen",
    email: "emily.chen@email.com",
    location: "🇸🇬",
    spent: "$2,800.00",
    persona: "High-value",
  },
];
